# We use a PHP image with Apache and Xdebug and extend it with Node so we we can start TC-app easily.
FROM webdevops/php-apache-dev:8.2 

# For more performance but less plugins and no Xdebug, use:
# FROM webdevops/php-apache:8.2

# Update the package index
RUN apt-get update && apt-get install -y curl

# Add the NodeSource repository for Node.js 18
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash -

# Install Node.js and npm
RUN apt-get install -y nodejs

# Verify installation
RUN node --version && npm --version

# Set the working directory
WORKDIR /app