services:

  # MySQL Database shared between WordPress, Team-Portal, and TC-App
  mysql_db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
      MYSQL_USER: ${MYSQL_USER:-wordpress}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-wordpress}
    volumes:
      - mysql_db:/var/lib/mysql
      - ./team-portal/php/scripts/Seeder_data.sql:/docker-entrypoint-initdb.d/Seeder_data.sql
      - ./tc-app/database_install.sql:/docker-entrypoint-initdb.d/database_install.sql
    ports:
      - "3306:3306"


  # Use WordPress image to create the necessary files.
  wordpress:
    image: wordpress:php8.2
    container_name: wordpress
    depends_on:
      - mysql_db
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST:-mysql_db:3306}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-${MYSQL_USER:-wordpress}}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-${MYSQL_PASSWORD:-wordpress}}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-${MYSQL_DATABASE:-wordpress}}
    volumes:
      - ./wordpress_data:/var/www/html


  # WP-CLI container
  wpcli:
    image: wordpress:cli
    container_name: wpcli
    depends_on:
      - wordpress
      - team-portal-frontend
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST_CLI:-${WORDPRESS_DB_HOST:-mysql_db}}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-${MYSQL_USER:-wordpress}}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-${MYSQL_PASSWORD:-wordpress}}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-${MYSQL_DATABASE:-wordpress}}
    volumes:
      - ./wordpress_data:/var/www/html
      - ./scripts/wait-for-it.sh:/wait-for-it.sh
      - ./scripts/wordpress_startup.sh:/wordpress_startup.sh
      - ./scripts/pods.json:/pods.json
    user: "33"
    entrypoint: >
      sh -c "set -e; sh /wordpress_startup.sh"


  # Apache webserver + PHP + Xdebug + Node
  apache-webserver:
    build:
      context: .
      dockerfile: Dockerfile-apache-webserver-php-xdebug-node
    container_name: apache-webserver
    depends_on:
      - mysql_db
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST:-mysql_db:3306}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-${MYSQL_USER:-wordpress}}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-${MYSQL_PASSWORD:-wordpress}}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-${MYSQL_DATABASE:-wordpress}}
    volumes:
      - ./wordpress_data:/app/
      - ./team-portal:/app/team-portal/
      - ./tc-app:/app/tc-app/
      - ./scripts/php.ini:/opt/docker/etc/php/php.ini
      - ./scripts/tmp:/tmp/
    command: bash -c "
      cd /app/team-portal/php && composer install &&
      cp /app/team-portal/php/.env.example /app/team-portal/php/.env &&
      cd /app/tc-app && composer install &&
      composer dump-autoload &&
      cd /app/tc-app && npm i &&
      cp /app/tc-app/.env.example /app/tc-app/.env &&
      rm /tmp/xdebug.log && touch /tmp/xdebug.log &&
      /usr/bin/supervisord -c /opt/docker/etc/supervisor.conf"


  # Team Portal Angular Frontend
  team-portal-frontend:
    build:
      context: ./team-portal
      dockerfile: ./Dockerfile-frontend
    container_name: team-portal-frontend
    depends_on:
      - apache-webserver
    ports:
      - "4200:4200"
    volumes:
      - ./team-portal:/app
      - team-portal-node_modules:/app/node_modules


volumes:
  mysql_db:
  team-portal-node_modules:
